function CodeDefine() { 
this.def = new Array();
this.def["dual_motor_B"] = {file: "dual_motor_c.html",line:49,type:"var"};
this.def["dual_motor_DW"] = {file: "dual_motor_c.html",line:52,type:"var"};
this.def["dual_motor_M_"] = {file: "dual_motor_c.html",line:55,type:"var"};
this.def["dual_motor_M"] = {file: "dual_motor_c.html",line:56,type:"var"};
this.def["dual_motor_step"] = {file: "dual_motor_c.html",line:59,type:"fcn"};
this.def["dual_motor_initialize"] = {file: "dual_motor_c.html",line:86,type:"fcn"};
this.def["B_dual_motor"] = {file: "dual_motor_h.html",line:105,type:"type"};
this.def["DW_dual_motor"] = {file: "dual_motor_h.html",line:161,type:"type"};
this.def["RT_MODEL_dual_motor"] = {file: "dual_motor_types_h.html",line:44,type:"type"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:49,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:73,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:84,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:108,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:49,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:73,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:48,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:49,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:50,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:51,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:52,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:53,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:59,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:71,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:77,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:83,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:105,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:59,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:66,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:73,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:84,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:85,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:86,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:88,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:89,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:90,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:108,type:"type"};
this.def["endif"] = {file: "dual_motor_EXTI_c.html",line:75,type:"fcn"};
this.def["HAL_GPIO_EXTI_Callback"] = {file: "dual_motor_EXTI_c.html",line:50,type:"fcn"};
this.def["EXTI0_Callback"] = {file: "dual_motor_EXTI_c.html",line:129,type:"fcn"};
this.def["G_TIM_Count"] = {file: "dual_motor_TIM_c.html",line:42,type:"var"};
this.def["G_TIM_Conf"] = {file: "dual_motor_TIM_c.html",line:45,type:"var"};
this.def["G_TIM_Handler"] = {file: "dual_motor_TIM_c.html",line:46,type:"var"};
this.def["TIM6_Conf"] = {file: "dual_motor_TIM_c.html",line:49,type:"var"};
this.def["G_TIM6_PollTimeOut"] = {file: "dual_motor_TIM_c.html",line:52,type:"var"};
this.def["TIM7_Conf"] = {file: "dual_motor_TIM_c.html",line:55,type:"var"};
this.def["G_TIM7_PollTimeOut"] = {file: "dual_motor_TIM_c.html",line:58,type:"var"};
this.def["TIM3_Conf"] = {file: "dual_motor_TIM_c.html",line:61,type:"var"};
this.def["G_TIM3_PollTimeOut"] = {file: "dual_motor_TIM_c.html",line:64,type:"var"};
this.def["TIM4_Conf"] = {file: "dual_motor_TIM_c.html",line:67,type:"var"};
this.def["G_TIM4_PollTimeOut"] = {file: "dual_motor_TIM_c.html",line:70,type:"var"};
this.def["TIM9_Conf"] = {file: "dual_motor_TIM_c.html",line:73,type:"var"};
this.def["G_TIM9_PollTimeOut"] = {file: "dual_motor_TIM_c.html",line:76,type:"var"};
this.def["TIM_PeriodElapsedCustomCallback"] = {file: "dual_motor_TIM_c.html",line:83,type:"fcn"};
this.def["HAL_TIM_PeriodElapsedCallback"] = {file: "dual_motor_TIM_c.html",line:112,type:"fcn"};
this.def["TIM6_ItUpFcn"] = {file: "dual_motor_TIM_c.html",line:127,type:"fcn"};
this.def["TIM7_ItUpFcn"] = {file: "dual_motor_TIM_c.html",line:565,type:"fcn"};
this.def["TIM_ConfTypeDef"] = {file: "dual_motor_TIM_h.html",line:99,type:"type"};
this.def["TIM_ChTypeDef"] = {file: "dual_motor_TIM_h.html",line:112,type:"type"};
this.def["G_USART3_TxPollTimeOut"] = {file: "dual_motor_USART_c.html",line:43,type:"var"};
this.def["G_SERIAL_TX_Count"] = {file: "dual_motor_USART_c.html",line:46,type:"var"};
this.def["G_SERIAL_TX_Conf"] = {file: "dual_motor_USART_c.html",line:49,type:"var"};
this.def["G_SERIAL_TX_Handler"] = {file: "dual_motor_USART_c.html",line:50,type:"var"};
this.def["dual_motor_USART.c:USART3_TxDataBuffer"] = {file: "dual_motor_USART_c.html",line:53,type:"var"};
this.def["USART3_TxConf"] = {file: "dual_motor_USART_c.html",line:56,type:"var"};
this.def["TX_CopyData"] = {file: "dual_motor_USART_c.html",line:64,type:"fcn"};
this.def["HAL_UART_TxCpltCallback"] = {file: "dual_motor_USART_c.html",line:103,type:"fcn"};
this.def["USART3_TX_SendData"] = {file: "dual_motor_USART_c.html",line:127,type:"fcn"};
this.def["USART3_Tx_Initialization"] = {file: "dual_motor_USART_c.html",line:175,type:"fcn"};
this.def["SERIAL_TxStatusTypeDef"] = {file: "dual_motor_USART_h.html",line:52,type:"type"};
this.def["SERIAL_TxConfTypeDef"] = {file: "dual_motor_USART_h.html",line:71,type:"type"};
this.def["main.c:OverrunFlags"] = {file: "main_c.html",line:45,type:"var"};
this.def["main.c:autoReloadTimerLoopVal_S"] = {file: "main_c.html",line:48,type:"var"};
this.def["remainAutoReloadTimerLoopVal_S"] = {file: "main_c.html",line:51,type:"var"};
this.def["main"] = {file: "main_c.html",line:59,type:"fcn"};
this.def["SysTick_Handler"] = {file: "stm32xxxx_it_c.html",line:41,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["dual_motor_c.html"] = "../dual_motor.c";
	this.html2Root["dual_motor_c.html"] = "dual_motor_c.html";
	this.html2SrcPath["dual_motor_h.html"] = "../dual_motor.h";
	this.html2Root["dual_motor_h.html"] = "dual_motor_h.html";
	this.html2SrcPath["dual_motor_private_h.html"] = "../dual_motor_private.h";
	this.html2Root["dual_motor_private_h.html"] = "dual_motor_private_h.html";
	this.html2SrcPath["dual_motor_types_h.html"] = "../dual_motor_types.h";
	this.html2Root["dual_motor_types_h.html"] = "dual_motor_types_h.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["STM32_Config_h.html"] = "../STM32_Config.h";
	this.html2Root["STM32_Config_h.html"] = "STM32_Config_h.html";
	this.html2SrcPath["dual_motor_EXTI_c.html"] = "../dual_motor_EXTI.c";
	this.html2Root["dual_motor_EXTI_c.html"] = "dual_motor_EXTI_c.html";
	this.html2SrcPath["dual_motor_EXTI_h.html"] = "../dual_motor_EXTI.h";
	this.html2Root["dual_motor_EXTI_h.html"] = "dual_motor_EXTI_h.html";
	this.html2SrcPath["dual_motor_External_Functions_h.html"] = "../dual_motor_External_Functions.h";
	this.html2Root["dual_motor_External_Functions_h.html"] = "dual_motor_External_Functions_h.html";
	this.html2SrcPath["dual_motor_TIM_c.html"] = "../dual_motor_TIM.c";
	this.html2Root["dual_motor_TIM_c.html"] = "dual_motor_TIM_c.html";
	this.html2SrcPath["dual_motor_TIM_h.html"] = "../dual_motor_TIM.h";
	this.html2Root["dual_motor_TIM_h.html"] = "dual_motor_TIM_h.html";
	this.html2SrcPath["dual_motor_USART_c.html"] = "../dual_motor_USART.c";
	this.html2Root["dual_motor_USART_c.html"] = "dual_motor_USART_c.html";
	this.html2SrcPath["dual_motor_USART_h.html"] = "../dual_motor_USART.h";
	this.html2Root["dual_motor_USART_h.html"] = "dual_motor_USART_h.html";
	this.html2SrcPath["getBuffPtr_h.html"] = "../../../../../../../MATLAB/STM32-MAT/STM32/addSrc/inc/getBuffPtr.h";
	this.html2Root["getBuffPtr_h.html"] = "getBuffPtr_h.html";
	this.html2SrcPath["main_c.html"] = "../main.c";
	this.html2Root["main_c.html"] = "main_c.html";
	this.html2SrcPath["stm32xxxx_it_c.html"] = "../stm32xxxx_it.c";
	this.html2Root["stm32xxxx_it_c.html"] = "stm32xxxx_it_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"dual_motor_c.html","dual_motor_h.html","dual_motor_private_h.html","dual_motor_types_h.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","STM32_Config_h.html","dual_motor_EXTI_c.html","dual_motor_EXTI_h.html","dual_motor_External_Functions_h.html","dual_motor_TIM_c.html","dual_motor_TIM_h.html","dual_motor_USART_c.html","dual_motor_USART_h.html","getBuffPtr_h.html","main_c.html","stm32xxxx_it_c.html"];
